"""add field active on store model

Revision ID: 362319c8973b
Revises: 3e132b795b56
Create Date: 2022-07-12 14:46:00.966713

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362319c8973b'
down_revision = '3e132b795b56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'active')
    # ### end Alembic commands ###
