[default]
DEBUG = false
APP_NAME = "pyfoods"
FLASK_ADMIN_SWATCH = "united"
ADMIN_NAME = "pyfoods default"
ADMIN_TEMPLATE_MODE = "bootstrap3"
EXTENSIONS = [
    "pyfoods.ext.db:init_app",
    "pyfoods.ext.auth:init_app",
    "pyfoods.ext.admin:init_app",
    "pyfoods.ext.migrate:init_app",
    "pyfoods.ext.cli:init_app",
    "pyfoods.ext.site:init_app",
    "pyfoods.ext.hooks:init_app",
]
UPLOAD_FOLDER = "uploads"

[development]
DEBUG = true
SQLALCHEMY_DATABASE_URI = "sqlite:///delivery.db"
SQLALCHEMY_TRACK_MODIFICATIONS = true
DEBUG_TB_TEMPLATE_EDITOR_ENABLED = true
DEBUG_TB_PROFILER_ENABLED = true
DEBUG_TB_INTERCEPT_REDIRECTS = false
ADMIN_NAME = "pyfoods Dev"
EXTENSIONS = [
    "dynaconf_merge",
    "pyfoods.ext.toolbar:init_app",
]

[production]
SQLALCHEMY_TRACK_MODIFICATIONS = false
SQLALCHEMY_DATABASE_URI = "postgresql:///..."